hosts:
  - name: "Ingelap-Web"
    host: "186.155.203.112"
    port: 2222 
    user: "wgp"
    key_path: "/ssh_keys/id_rsa"
    log_files:
      - path: "/var/log/nginx/access.log"
        type: "apache-combined"
      - path: "/var/log/nginx/landing_page_ingelap.access.log"
        type: "apache-combined"

#  - name: "web-server-02"
#    host: "192.168.1.20"
#    user: "ubuntu"
#    key_path: "/ssh_keys/id_rsa_web02" 
#    log_files:
#      - path: "/var/log/apache2/access.log"
#        type: "apache-combined"
