apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432 # Docker service name
    user: wmc_user
    database: wmc_db
    jsonData:
      sslmode: "disable" # For internal docker net
      postgresVersion: 1000 # >= 10
      timescaledb: false
    secureJsonData:
      password: wmc_password
    isDefault: true
    editable: true
