apiVersion: apps/v1
kind: Deployment
metadata:
  name: wmc-log-processor
spec:
  selector:
    matchLabels:
      app: wmc-log-processor
  template:
    metadata:
      labels:
        app: wmc-log-processor
    spec:
      containers:
      - name: log-processor
        image: gersonofstone/web_metrics_collector:latest
        env:
        - name: DB_HOST
          value: "postgres"
        - name: DB_NAME
          value: "wmc_db"
        - name: DB_USER
          value: "wmc_user"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wmc-secrets
              key: POSTGRES_PASSWORD
        - name: GEOIP_LICENSE_KEY
          valueFrom:
            secretKeyRef:
              name: wmc-secrets
              key: GEOIP_LICENSE_KEY
        - name: CONFIG_FILE
          value: "/app/hosts.yml"
        volumeMounts:
        - name: config
          mountPath: /app/hosts.yml
          subPath: hosts.yml
        - name: ssh-keys
          mountPath: /ssh_keys
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: wmc-config
      - name: ssh-keys
        secret:
          secretName: wmc-ssh-keys
          defaultMode: 0400
