apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: wmc-postgres
  ports:
  - port: 5432
    targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wmc-postgres
spec:
  selector:
    matchLabels:
      app: wmc-postgres
  template:
    metadata:
      labels:
        app: wmc-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:16
        env:
        - name: POSTGRES_USER
          value: "wmc_user"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wmc-secrets
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          value: "wmc_db"
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
        - name: init-sql
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: wmc-postgres-pvc
      - name: init-sql
        configMap:
          name: wmc-init-sql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wmc-postgres-pvc
spec:
  storageClassName: nfs-client # Replace with your actual StorageClass name (e.g., gp2, managed-premium, etc.)
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
